openapi: 3.0.0
info:
  title: Group Projects API
  version: 1.0.0
paths:
  /api/projects:
    get:
      summary: Get all group projects
      tags:
        - GroupProject
      responses:
        '200':
          description: List of group projects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GroupProject'
components:
  schemas:
    GroupProject:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        image:
          type: string
        distance:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
